/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StockFind {
    }
    interface StockPrice {
        "stockSymbol": string;
    }
    interface UcSpinner {
    }
}
declare global {
    interface HTMLStockFindElement extends Components.StockFind, HTMLStencilElement {
    }
    var HTMLStockFindElement: {
        prototype: HTMLStockFindElement;
        new (): HTMLStockFindElement;
    };
    interface HTMLStockPriceElement extends Components.StockPrice, HTMLStencilElement {
    }
    var HTMLStockPriceElement: {
        prototype: HTMLStockPriceElement;
        new (): HTMLStockPriceElement;
    };
    interface HTMLUcSpinnerElement extends Components.UcSpinner, HTMLStencilElement {
    }
    var HTMLUcSpinnerElement: {
        prototype: HTMLUcSpinnerElement;
        new (): HTMLUcSpinnerElement;
    };
    interface HTMLElementTagNameMap {
        "stock-find": HTMLStockFindElement;
        "stock-price": HTMLStockPriceElement;
        "uc-spinner": HTMLUcSpinnerElement;
    }
}
declare namespace LocalJSX {
    interface StockFind {
        "onUcSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface StockPrice {
        "stockSymbol"?: string;
    }
    interface UcSpinner {
    }
    interface IntrinsicElements {
        "stock-find": StockFind;
        "stock-price": StockPrice;
        "uc-spinner": UcSpinner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stock-find": LocalJSX.StockFind & JSXBase.HTMLAttributes<HTMLStockFindElement>;
            "stock-price": LocalJSX.StockPrice & JSXBase.HTMLAttributes<HTMLStockPriceElement>;
            "uc-spinner": LocalJSX.UcSpinner & JSXBase.HTMLAttributes<HTMLUcSpinnerElement>;
        }
    }
}
